export const ICON_OPTIONS = [
  { value: 'fa-university', label: 'University' },
  { value: 'fa-book-quran', label: 'Quran' },
  { value: 'fa-mosque', label: 'Mosque' },
  { value: 'fa-microchip', label: 'Microchip' },
  { value: 'fa-chart-line', label: 'Chart' },
  { value: 'fa-pen-fancy', label: 'Pen' },
  { value: 'fa-gavel', label: 'Gavel' },
  { value: 'fa-graduation-cap', label: 'Graduation' },
  { value: 'fa-building', label: 'Building' },
  { value: 'fa-laptop-code', label: 'Laptop Code' },
  { value: 'fa-bolt', label: 'Bolt' },
  { value: 'fa-wifi', label: 'WiFi' },
  { value: 'fa-tower-broadcast', label: 'Tower' },
  { value: 'fa-pills', label: 'Pills' },
  { value: 'fa-briefcase', label: 'Briefcase' },
  { value: 'fa-coins', label: 'Coins' },
  { value: 'fa-language', label: 'Language' },
  { value: 'fa-font', label: 'Font' },
  { value: 'fa-book-open', label: 'Book Open' },
  { value: 'fa-heart', label: 'Heart' },
  { value: 'fa-flask', label: 'Flask' },
  { value: 'fa-atom', label: 'Atom' },
  { value: 'fa-brain', label: 'Brain' },
  { value: 'fa-dna', label: 'DNA' },
  { value: 'fa-stethoscope', label: 'Stethoscope' },
  { value: 'fa-heartbeat', label: 'Heartbeat' },
  { value: 'fa-balance-scale', label: 'Balance Scale' },
  { value: 'fa-landmark', label: 'Landmark' },
  { value: 'fa-book', label: 'Book' },
  { value: 'fa-users', label: 'Users' },
  { value: 'fa-user-graduate', label: 'Graduate' },
  { value: 'fa-chalkboard-teacher', label: 'Teacher' },
  { value: 'fa-cogs', label: 'Cogs' },
  { value: 'fa-network-wired', label: 'Network' },
  { value: 'fa-database', label: 'Database' },
];
