export const config = {
  owner: 'sayedatiqurrahman',
  repo: 'QSIS-ACADEMIC-FILES-MANAFGER',
  branch: 'main',
  uploadPath: 'upload_academic_files',
  relatedKitabsFolder: 'related-kitabs',
  founderName: 'Sayed Atiqur Rahman',
  founderAgency: 'Programming Light',
  adobeClientId: process.env.NEXT_PUBLIC_ADOBE_CLIENT_ID || '',
  recaptchaSiteKey: process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY || '',
  emailRegex: /^q\d{5,8}@ugrad\.iiuc\.ac\.bd$/i,
  ownerEmails: [
    'quranicsciencesclub@gmail.com',
    's.atiqurrahman2003@gmail.com',
  ],
  maxFilesPerUpload: 10,
  maxUploadSizeMB: 50,
  academicExtensions: ['pdf','doc','docx','xls','xlsx','ppt','pptx','jpg','jpeg','png','webp','csv'],
  semesters: [
    { id: '1st-semister', label: '1st Semester' },
    { id: '2nd-semister', label: '2nd Semester' },
    { id: '3rd-semister', label: '3rd Semester' },
    { id: '4th-semister', label: '4th Semester' },
    { id: '5th-semister', label: '5th Semester' },
    { id: '6th-semister', label: '6th Semester' },
    { id: '7th-semister', label: '7th Semester' },
    { id: '8th-semister', label: '8th Semester' },
  ],
  categories: {
    sheet: { label: 'Sheets', icon: 'scroll', color: '#3b82f6' },
    question: { label: 'Previous Questions', icon: 'question-circle', color: '#f59e0b' },
    note: { label: 'Notes', icon: 'sticky-note', color: '#22c55e' },
    syllabus: { label: 'Syllabus', icon: 'graduation-cap', color: '#8b5cf6' },
    other: { label: 'Other', icon: 'folder', color: '#94a3b8' },
  },
  relatedKitabsCategories: {
    'quran-tafsir': { label: 'Quran & Tafsir', icon: 'book-quran', color: '#10b981' },
    'hadith': { label: 'Hadith', icon: 'book', color: '#f97316' },
    'fiqh': { label: 'Fiqh', icon: 'balance-scale', color: '#6366f1' },
    'aqeedah': { label: 'Aqeedah', icon: 'mosque', color: '#ec4899' },
    'seerah': { label: 'Seerah', icon: 'user-graduate', color: '#14b8a6' },
    'general': { label: 'General', icon: 'folder-open', color: '#94a3b8' },
  },
};
