const DEFAULT_PERMISSIONS: Record<string, string[]> = {
  addCourse: ['admin', 'manager', 'teacher', 'cr', 'student', 'user'],
  addToAnySemester: [],
  createFolder: ['admin', 'manager', 'teacher', 'cr', 'student', 'user'],
  editCourse: ['admin', 'manager', 'teacher', 'cr'],
  deleteCourse: ['admin', 'manager', 'teacher'],
  uploadFile: ['admin', 'manager', 'teacher', 'cr', 'student'],
  uploadAnySemester: [],
  uploadAnyDepartment: [],
  requireGithubForUpload: ['admin', 'manager', 'teacher', 'cr', 'student'],
  manageFaculty: ['admin', 'manager', 'teacher'],
  manageFacultyDepts: ['admin', 'manager'],
  publishRoutine: ['admin', 'manager', 'teacher', 'cr'],
  manageBatches: ['admin', 'manager', 'teacher', 'cr', 'acr'],
  manageUsers: ['admin', 'manager'],
  manageSettings: ['admin'],
  publishNotice: ['admin', 'manager', 'teacher'],
  manageCronJobs: ['admin'],
  moveFile: ['admin'],
  copyFile: ['admin'],
  renameFile: ['admin'],
  deleteFile: ['admin'],
  editLinks: ['admin', 'manager', 'teacher', 'cr'],
  saveCourseToGitHub: ['admin', 'manager', 'teacher', 'cr'],
  manageRooms: ['admin', 'manager', 'teacher'],
  viewExternalUsers: ['admin', 'manager'],
  publishTutorial: ['admin', 'manager', 'teacher'],
  publishBlog: ['admin', 'manager', 'teacher', 'cr'],
  createClub: ['admin', 'manager', 'teacher'],
  manageAllClubs: ['admin', 'manager'],
  manageClubMembers: ['admin', 'manager', 'teacher'],
  manageClubEvents: ['admin', 'manager', 'teacher'],
  issueCertificates: ['admin', 'manager', 'teacher'],
};

export { DEFAULT_PERMISSIONS };
