// Bilingual English <-> Arabic glossary of common academic/research terms.

export interface GlossaryTerm {
  en: string;
  ar: string;
  category: string;
}

export const GLOSSARY_CATEGORIES = [
  'Research Methods',
  'Academic Writing',
  'Statistics',
  'Library & Sources',
  'Publishing',
] as const;

export const GLOSSARY: GlossaryTerm[] = [
  { en: 'Research', ar: 'بحث', category: 'Research Methods' },
  { en: 'Research methodology', ar: 'منهجية البحث', category: 'Research Methods' },
  { en: 'Qualitative research', ar: 'البحث النوعي', category: 'Research Methods' },
  { en: 'Quantitative research', ar: 'البحث الكمي', category: 'Research Methods' },
  { en: 'Mixed methods', ar: 'المناهج المختلطة', category: 'Research Methods' },
  { en: 'Hypothesis', ar: 'فرضية', category: 'Research Methods' },
  { en: 'Research question', ar: 'سؤال البحث', category: 'Research Methods' },
  { en: 'Objective', ar: 'هدف', category: 'Research Methods' },
  { en: 'Independent variable', ar: 'متغير مستقل', category: 'Research Methods' },
  { en: 'Dependent variable', ar: 'متغير تابع', category: 'Research Methods' },
  { en: 'Control group', ar: 'مجموعة ضابطة', category: 'Research Methods' },
  { en: 'Sample', ar: 'عينة', category: 'Research Methods' },
  { en: 'Sampling', ar: 'أخذ العينات', category: 'Research Methods' },
  { en: 'Population', ar: 'مجتمع الدراسة', category: 'Research Methods' },
  { en: 'Respondent', ar: 'مستجيب', category: 'Research Methods' },
  { en: 'Questionnaire', ar: 'استبيان', category: 'Research Methods' },
  { en: 'Interview', ar: 'مقابلة', category: 'Research Methods' },
  { en: 'Focus group', ar: 'مجموعة بؤرية', category: 'Research Methods' },
  { en: 'Observation', ar: 'ملاحظة', category: 'Research Methods' },
  { en: 'Case study', ar: 'دراسة حالة', category: 'Research Methods' },
  { en: 'Comparative study', ar: 'دراسة مقارنة', category: 'Research Methods' },
  { en: 'Longitudinal study', ar: 'دراسة طولية', category: 'Research Methods' },
  { en: 'Cross-sectional study', ar: 'دراسة مقطعية', category: 'Research Methods' },
  { en: 'Experiment', ar: 'تجربة', category: 'Research Methods' },
  { en: 'Field study', ar: 'دراسة ميدانية', category: 'Research Methods' },
  { en: 'Triangulation', ar: 'التثليث (تعدد الأساليب)', category: 'Research Methods' },
  { en: 'Validity', ar: 'صدق', category: 'Research Methods' },
  { en: 'Reliability', ar: 'ثبات', category: 'Research Methods' },
  { en: 'Bias', ar: 'انحياز', category: 'Research Methods' },
  { en: 'Ethics', ar: 'أخلاقيات البحث', category: 'Research Methods' },
  { en: 'Consent', ar: 'موافقة', category: 'Research Methods' },
  { en: 'Confidentiality', ar: 'سرية', category: 'Research Methods' },
  { en: 'Data collection', ar: 'جمع البيانات', category: 'Research Methods' },
  { en: 'Data analysis', ar: 'تحليل البيانات', category: 'Research Methods' },
  { en: 'Empirical', ar: 'تجريبي', category: 'Research Methods' },
  { en: 'Theoretical framework', ar: 'الإطار النظري', category: 'Research Methods' },
  { en: 'Conceptual framework', ar: 'الإطار المفاهيمي', category: 'Research Methods' },
  { en: 'Gap in research', ar: 'الفجوة البحثية', category: 'Research Methods' },
  { en: 'Recommendations', ar: 'التوصيات', category: 'Research Methods' },
  { en: 'Limitations', ar: 'حدود الدراسة', category: 'Research Methods' },
  { en: 'Abstract', ar: 'ملخص', category: 'Academic Writing' },
  { en: 'Introduction', ar: 'مقدمة', category: 'Academic Writing' },
  { en: 'Literature review', ar: 'مراجعة الأدبيات', category: 'Academic Writing' },
  { en: 'Methodology', ar: 'منهجية', category: 'Academic Writing' },
  { en: 'Results', ar: 'النتائج', category: 'Academic Writing' },
  { en: 'Findings', ar: 'النتائج المتوصل إليها', category: 'Academic Writing' },
  { en: 'Discussion', ar: 'المناقشة', category: 'Academic Writing' },
  { en: 'Conclusion', ar: 'الخاتمة', category: 'Academic Writing' },
  { en: 'References', ar: 'المراجع', category: 'Academic Writing' },
  { en: 'Bibliography', ar: 'قائمة المراجع', category: 'Academic Writing' },
  { en: 'Citation', ar: 'استشهاد', category: 'Academic Writing' },
  { en: 'Plagiarism', ar: 'انتحال', category: 'Academic Writing' },
  { en: 'Paraphrasing', ar: 'إعادة الصياغة', category: 'Academic Writing' },
  { en: 'Quotation', ar: 'اقتباس', category: 'Academic Writing' },
  { en: 'Footnotes', ar: 'هوامش', category: 'Academic Writing' },
  { en: 'Thesis statement', ar: 'الأطروحة', category: 'Academic Writing' },
  { en: 'Argument', ar: 'حجة', category: 'Academic Writing' },
  { en: 'Evidence', ar: 'دليل', category: 'Academic Writing' },
  { en: 'Coherence', ar: 'الترابط', category: 'Academic Writing' },
  { en: 'Cohesion', ar: 'التماسك', category: 'Academic Writing' },
  { en: 'Clarity', ar: 'وضوح', category: 'Academic Writing' },
  { en: 'Conciseness', ar: 'الإيجاز', category: 'Academic Writing' },
  { en: 'Academic tone', ar: 'الأسلوب الأكاديمي', category: 'Academic Writing' },
  { en: 'Formal language', ar: 'اللغة الرسمية', category: 'Academic Writing' },
  { en: 'Terminology', ar: 'مصطلحات', category: 'Academic Writing' },
  { en: 'Abbreviation', ar: 'اختصار', category: 'Academic Writing' },
  { en: 'Table of contents', ar: 'فهرس المحتويات', category: 'Academic Writing' },
  { en: 'Appendix', ar: 'ملحق', category: 'Academic Writing' },
  { en: 'Peer review', ar: 'مراجعة النظراء', category: 'Publishing' },
  { en: 'Journal', ar: 'مجلة', category: 'Publishing' },
  { en: 'Academic journal', ar: 'مجلة أكاديمية', category: 'Publishing' },
  { en: 'Journal article', ar: 'مقالة في مجلة', category: 'Publishing' },
  { en: 'Impact factor', ar: 'معامل التأثير', category: 'Publishing' },
  { en: 'Conference', ar: 'مؤتمر', category: 'Publishing' },
  { en: 'Proceedings', ar: 'وقائع المؤتمر', category: 'Publishing' },
  { en: 'Manuscript', ar: 'مخطوطة', category: 'Publishing' },
  { en: 'Submission', ar: 'تقديم', category: 'Publishing' },
  { en: 'Publication', ar: 'نشر', category: 'Publishing' },
  { en: 'Publisher', ar: 'ناشر', category: 'Publishing' },
  { en: 'Editor', ar: 'محرر', category: 'Publishing' },
  { en: 'Author', ar: 'مؤلف', category: 'Publishing' },
  { en: 'Co-author', ar: 'مؤلف مشارك', category: 'Publishing' },
  { en: 'Corresponding author', ar: 'المراسل', category: 'Publishing' },
  { en: 'Copyright', ar: 'حقوق النشر', category: 'Publishing' },
  { en: 'Open access', ar: 'الوصول المفتوح', category: 'Publishing' },
  { en: 'DOI', ar: 'معرف الكائن الرقمي (DOI)', category: 'Publishing' },
  { en: 'ISSN', ar: 'الرقم الدولي الموحد للدوريات (ISSN)', category: 'Publishing' },
  { en: 'ISBN', ar: 'الرقم الدولي الموحد للكتاب (ISBN)', category: 'Publishing' },
  { en: 'Library', ar: 'مكتبة', category: 'Library & Sources' },
  { en: 'Archive', ar: 'أرشيف', category: 'Library & Sources' },
  { en: 'Database', ar: 'قاعدة بيانات', category: 'Library & Sources' },
  { en: 'Repository', ar: 'مستودع', category: 'Library & Sources' },
  { en: 'Index', ar: 'فهرس', category: 'Library & Sources' },
  { en: 'Primary source', ar: 'مصدر أولي', category: 'Library & Sources' },
  { en: 'Secondary source', ar: 'مصدر ثانوي', category: 'Library & Sources' },
  { en: 'Manuscript', ar: 'مخطوطة', category: 'Library & Sources' },
  { en: 'Encyclopedia', ar: 'موسوعة', category: 'Library & Sources' },
  { en: 'Dictionary', ar: 'قاموس', category: 'Library & Sources' },
  { en: 'Monograph', ar: 'دراسة متخصصة', category: 'Library & Sources' },
  { en: 'Verse (Qur’an)', ar: 'آية', category: 'Library & Sources' },
  { en: 'Sūrah', ar: 'سورة', category: 'Library & Sources' },
  { en: 'Hadith', ar: 'حديث', category: 'Library & Sources' },
  { en: 'Tafsir', ar: 'تفسير', category: 'Library & Sources' },
  { en: "Sabab al-nuzul (occasion of revelation)", ar: 'سبب النزول', category: 'Library & Sources' },
  { en: 'Fiqh (jurisprudence)', ar: 'فقه', category: 'Library & Sources' },
  { en: 'Tahqiq (critical edition)', ar: 'تحقيق', category: 'Library & Sources' },
  { en: 'Mean', ar: 'المتوسط الحسابي', category: 'Statistics' },
  { en: 'Median', ar: 'الوسيط', category: 'Statistics' },
  { en: 'Mode', ar: 'المنوال', category: 'Statistics' },
  { en: 'Standard deviation', ar: 'الانحراف المعياري', category: 'Statistics' },
  { en: 'Variance', ar: 'التباين', category: 'Statistics' },
  { en: 'Correlation', ar: 'ارتباط', category: 'Statistics' },
  { en: 'Regression', ar: 'انحدار', category: 'Statistics' },
  { en: 'Frequency', ar: 'تكرار', category: 'Statistics' },
  { en: 'Percentage', ar: 'نسبة مئوية', category: 'Statistics' },
  { en: 'Probability', ar: 'احتمال', category: 'Statistics' },
  { en: 'Significance', ar: 'دلالة إحصائية', category: 'Statistics' },
  { en: 'p-value', ar: 'قيمة الاحتمال (p)', category: 'Statistics' },
  { en: 'Confidence interval', ar: 'فاصل الثقة', category: 'Statistics' },
  { en: 'Normal distribution', ar: 'التوزيع الطبيعي', category: 'Statistics' },
  { en: 'Chi-square test', ar: 'اختبار مربع كاي', category: 'Statistics' },
  { en: 't-test', ar: 'اختبار ت', category: 'Statistics' },
  { en: 'ANOVA', ar: 'تحليل التباين (ANOVA)', category: 'Statistics' },
  { en: 'Descriptive statistics', ar: 'إحصاء وصفي', category: 'Statistics' },
  { en: 'Inferential statistics', ar: 'إحصاء استدلالي', category: 'Statistics' },
];

export function searchGlossary(q: string): GlossaryTerm[] {
  const needle = q.trim().toLowerCase();
  if (!needle) return GLOSSARY;
  return GLOSSARY.filter(
    (t) =>
      t.en.toLowerCase().includes(needle) ||
      t.ar.includes(q.trim()) ||
      t.category.toLowerCase().includes(needle)
  );
}